import Foundation

var reattached = KernelRecoveryState()
assert(reattached.scene("previous-owner", foreground: true)!.0)
assert(reattached.replaceScenes(["current-owner"]) == nil)
assert(reattached.scenes == ["current-owner"])
assert(reattached.scene("current-owner", foreground: false)!.0 == false)
assert(reattached.scenes.isEmpty)
assert(reattached.replaceScenes(["current-owner"])!.0)
assert(!reattached.command(false).0)
assert(reattached.replaceScenes(["current-owner"]) == nil)
assert(reattached.desired == false)
print("PASS: owner reattachment replaces stale scenes and preserves explicit cancellation")

// viewDidLoad registers and returns while the connecting scene is not yet
// foreground. Its later lifecycle event can now activate the listener.
var cold = KernelRecoveryState()
assert(cold.scene("connecting", foreground: false)!.0 == false)
cold.requestInitialTransport()
assert(!cold.takeInitialTransport())
assert(cold.scene("connecting", foreground: true)!.0)
assert(!cold.receive(.init(requestID: 1, generation: 0, state: "TransportAccepting", detail: "")))
assert(!cold.takeInitialTransport())
assert(cold.receive(.init(requestID: 2, generation: 1, state: "Failed", detail: "bind")))
assert(!cold.takeInitialTransport())
assert(cold.command(true).1 == 3)
assert(cold.receive(.init(requestID: 3, generation: 2, state: "TransportAccepting", detail: "")))
assert(cold.takeInitialTransport())
assert(!cold.takeInitialTransport())
// Late registration consumes the current snapshot, while a subsequent pause
// prevents a saved snapshot from releasing a new startup continuation.
cold.requestInitialTransport()
assert(cold.takeInitialTransport())
assert(cold.scene("connecting", foreground: false)!.0 == false)
cold.requestInitialTransport()
assert(!cold.takeInitialTransport())
assert(cold.scene("connecting", foreground: true)!.0)
assert(!cold.takeInitialTransport())
assert(cold.receive(.init(requestID: 5, generation: 3, state: "TransportAccepting", detail: "")))
assert(cold.takeInitialTransport())
print("PASS: cold scene startup, late registration, one-shot continuation and stale snapshot fencing")

var state = KernelRecoveryState()
assert(state.scene("first", foreground: true)!.0)
assert(state.scene("first", foreground: true) == nil)
assert(state.scene("second", foreground: true) == nil)
assert(state.scene("first", foreground: false) == nil)
assert(state.scene("second", foreground: false)!.0 == false)
assert(state.scene("first", foreground: true)!.1 == 3)
assert(!state.receive(.init(requestID: 1, generation: 1, state: "TransportAccepting", detail: "")))
assert(state.receive(.init(requestID: 3, generation: 2, state: "TransportAccepting", detail: "")))
assert(state.bridgeReady("firstPage", navigation: 0))
assert(!state.acknowledge("unknown", page: "firstPage", request: 3, generation: 2))
assert(!state.recoveryCompleted)
assert(state.acknowledge("recoveryCompleted", page: "firstPage", request: 3, generation: 2))
assert(!state.recoveryCompleted)
assert(state.acknowledge("frontendConnected", page: "firstPage", request: 3, generation: 2))
assert(state.acknowledge("recoveryCompleted", page: "firstPage", request: 3, generation: 2))
assert(state.recoveryCompleted)
state.invalidatePage()
assert(!state.bridgeReady("oldPage", navigation: 0))
assert(!state.acknowledge("frontendConnected", page: "firstPage", request: 3, generation: 2))
assert(state.bridgeReady("newPage", navigation: 1))
assert(state.latest?.generation == 2)
assert(state.command(false).1 == 4)
assert(state.scene("first", foreground: true) == nil)
assert(!state.receive(.init(requestID: 3, generation: 2, state: "TransportAccepting", detail: "")))
print("PASS: scene aggregation, duplicate events, late callbacks, page fencing, ACK completion, cancellation")

for path in ["/stage/build/mobile", "/stage/build/mobile/", "/stage/build/desktop/", "/stage/build/desktop/index.html"] {
  assert(KernelRecoveryState.isTrustedURL(URL(string: "http://127.0.0.1:6806" + path), port: 6806))
}
assert(!KernelRecoveryState.isTrustedURL(URL(string: "http://127.0.0.1:6806/stage/build/mobileevil/"), port: 6806))
assert(!KernelRecoveryState.isTrustedURL(URL(string: "http://example.com:6806/stage/build/mobile/"), port: 6806))
assert(!KernelRecoveryState.isTrustedURL(URL(string: "http://127.0.0.1:6807/stage/build/mobile/"), port: 6806))
print("PASS: trusted directory URL normalization and origin/port boundaries")
